<?php
/**
 * 开店星新零售管理系统
 * @description 基于Yii2+Vue2.0+uniapp研发，H5+小程序+公众号全渠道覆盖，功能完善开箱即用，框架成熟易扩展二开
 * @author 青岛开店星信息技术有限公司
 * @link https://www.kaidianxing.com
 * @copyright Copyright (c) 2020-2022 Qingdao ShopStar Information Technology Co., Ltd.
 * @copyright 版权归青岛开店星信息技术有限公司所有
 * @warning Unauthorized deletion of copyright information is prohibited.
 * @warning 未经许可禁止私自删除版权信息
 */
return [
    'broadcast' => [
        'name' => '小程序直播',
        'type' => 10,
        'identity' => 'broadcast',
        'logo' =>  '/static/dist/shop/plugin_icon/icon-xcxLive.png',
        'description' => '实时视频互动，直播带货引导消费',
        'route' =>  '/liver/manage/list',
        'category' =>  30,
        'sort_by' =>  0,
    ],
    'material' => [
        'name' => '一键发圈',
        'type' => 10,
        'identity' => 'material',
        'logo' =>  '/static/dist/shop/plugin_icon/icon-material.png',
        'description' => '商品图文一键保存，便捷发布朋友圈',
        'route' =>  '/material/list',
        'category' =>  30,
        'sort_by' =>  0,
    ],

    'commentHelper' => [
        'name' => '评价助手',
        'type' => 10,
        'identity' => 'commentHelper',
        'logo' =>  '/static/dist/shop/plugin_icon/icon-commentHelper.png',
        'description' => '贴身评价小助手，高效提升转化率',
        'route' =>  '/commentHelper/comment/list',
        'category' =>  12,
        'sort_by' =>  0,
    ],
    'commission' => [
        'name' => '分销',
        'type' => 10,
        'identity' => 'commission',
        'logo' =>  '/static/dist/shop/plugin_icon/icon-distribution.png',
        'description' => '全民推广裂变，快速拓客销货',
        'route' =>  '/commission/index',
        'category' =>  11,
        'sort_by' =>  0,
    ],
    'groups' => [
        'name' => '多人拼团',
        'type' => 10,
        'identity' => 'groups',
        'logo' =>  '/static/dist/shop/plugin_icon/icon-groups.png',
        'description' => '多种拼团玩法，拉新转化翻倍',
        'route' =>  '/groups/activity/list',
        'category' =>  20,
        'sort_by' =>  99,
    ],
    'consumeReward' => [
        'name' => '消费奖励',
        'type' => 10,
        'identity' => 'consumeReward',
        'logo' =>  '/static/dist/shop/plugin_icon/icon-consumeReward.png',
        'description' => '消费优惠奖励，二次消费增加营收',
        'route' =>  '/consumeReward/activity/list',
        'category' =>  20,
        'sort_by' =>  0,
    ],
    'expressHelper' => [
        'name' => '快递助手',
        'type' => 10,
        'identity' => 'expressHelper',
        'logo' =>  '/static/dist/shop/plugin_icon/icon-eOrder.png',
        'description' => '电子面单+发货单，快速发货提升效率',
        'route' =>  '/eOrder/orderPrint/index',
        'category' =>  12,
        'sort_by' =>  0,
    ],
    'form' => [
        'name' => '系统表单',
        'type' => 10,
        'identity' => 'form',
        'logo' =>  '/static/dist/shop/plugin_icon/icon-systemForm.png',
        'description' => '多场景模板可选，信息收集多样化',
        'route' =>  '/systemForm/list',
        'category' =>  12,
        'sort_by' =>  0,
    ],
    'newGifts' => [
        'name' => '新人送礼',
        'type' => 10,
        'identity' => 'newGifts',
        'logo' =>  '/static/dist/shop/plugin_icon/icon-newGifts.png',
        'description' => '新人优惠奖励，高效拉新引导转化',
        'route' =>  '/newGifts/activity/index',
        'category' =>  20,
        'sort_by' =>  0,
    ],
    'notice' => [
        'name' => '消息通知',
        'type' => 10,
        'identity' => 'notice',
        'logo' =>  '/static/dist/shop/plugin_icon/icon-notice.png',
        'description' => '消息即时推送，短信自定义配置',
        'route' =>  '/notice/buyer/basic',
        'category' =>  12,
        'sort_by' =>  0,
    ],
    'poster' => [
        'name' => '超级海报',
        'type' => 10,
        'identity' => 'poster',
        'logo' =>  '/static/dist/shop/plugin_icon/icon-mallPoster.png',
        'description' => '快速生成海报，分享引流吸粉裂变',
        'route' =>  '/poster/list',
        'category' =>  20,
        'sort_by' =>  0,
    ],
    'printer' => [
        'name' => '打印小票',
        'type' => 10,
        'identity' => 'printer',
        'logo' =>  '/static/dist/shop/plugin_icon/icon-printer.png',
        'description' => '小票清单打印，订单信息一目了然',
        'route' =>  '/printer/manage/list',
        'category' =>  12,
        'sort_by' =>  0,
    ],
    'rechargeReward' => [
        'name' => '充值奖励',
        'type' => 10,
        'identity' => 'rechargeReward',
        'logo' =>  '/static/dist/shop/plugin_icon/icon-rechargeReward.png',
        'description' => '充值优惠奖励，鼓励预存推动消费',
        'route' =>  '/rechargeReward/activity/index',
        'category' =>  20,
        'sort_by' =>  0,
    ],
    'seckill' => [
        'name' => '秒杀活动',
        'type' => 10,
        'identity' => 'seckill',
        'logo' =>  '/static/dist/shop/plugin_icon/icon-seckill.png',
        'description' => '限时特价抢购，拉动店铺人气',
        'route' =>  '/seckill/activity/list',
        'category' =>  20,
        'sort_by' =>  0,
    ],
    'shoppingReward' => [
        'name' => '购物奖励',
        'type' => 10,
        'identity' => 'shoppingReward',
        'logo' =>  '/static/dist/shop/plugin_icon/icon-shoppingReward.png',
        'description' => '购物优惠奖励，打造爆款提升销量',
        'route' =>  '/shoppingReward/activity/index',
        'category' =>  20,
        'sort_by' =>  0,
    ],

    'wechat' => [
        'name' => '微信公众号',
        'type' => 20,
        'identity' => 'wechat',
        'logo' =>  '/static/dist/shop/channel_icon/icon_we_chat.png',
        'description' => '绑定微信服务号，打通您的店铺',
        'route' =>  '',
        'category' =>  0,
        'sort_by' =>  0,
    ],
    'wxapp' => [
        'name' => '微信小程序',
        'type' => 20,
        'identity' => 'wxapp',
        'logo' =>  '/static/dist/shop/channel_icon/icon_we_chat_applet.png',
        'description' => '将您的店铺生成到微信小程序',
        'route' =>  '',
        'category' =>  0,
        'sort_by' =>  0,
    ],

    'wap' => [
        'name' => '手机版',
        'type' => 20,
        'identity' => 'wap',
        'logo' =>  '/static/dist/shop/channel_icon/icon_browser.png',
        'description' => '通过手机浏览器访问您的店铺',
        'route' =>  '',
        'category' =>  0,
        'sort_by' =>  0,
    ],
    'virtualAccount' => [
        'name' => '虚拟卡密',
        'type' => 10,
        'identity' => 'virtualAccount',
        'logo' =>  '/static/dist/shop/plugin_icon/icon-virtualAccount.png',
        'description' => '多种类型覆盖，在线自动发卡',
        'route' =>  '/virtualAccount/library/list',
        'category' =>  10,
        'sort_by' =>  0,
    ],
    'wxTransactionComponent' => [
        'name' => '自定义交易组件(视频号商城)',
        'type' => 10,
        'identity' => 'wxTransactionComponent',
        'logo' =>  '/static/dist/shop/plugin_icon/icon-wxTransactionComponent.png',
        'description' => '链接微信视频号',
        'route' =>  '/wxTransactionComponent/index',
        'category' =>  12,
        'sort_by' =>  0,
    ],
    'douyin' => [
        'name' => '抖音小程序',
        'type' => 20,
        'identity' => 'douyin',
        'logo' =>  '/static/dist/shop/channel_icon/icon-douyin.png',
        'description' => '将您的店铺生成到抖音小程序',
        'route' =>  '',
        'category' =>  0,
        'sort_by' =>  0,
    ],
    'toutiao' => [
        'name' => '头条小程序',
        'type' => 20,
        'identity' => 'toutiao',
        'logo' =>  '/static/dist/shop/channel_icon/icon_toutiao.png',
        'description' => '将您的店铺生成到头条小程序',
        'route' =>  '',
        'category' =>  0,
        'sort_by' =>  0,
    ],
    'pc' => [
        'name' => 'PC版',
        'type' => 20,
        'identity' => 'pc',
        'logo' =>  '/static/dist/shop/channel_icon/icon_pc.png',
        'description' => '通过PC浏览器访问您的店铺',
        'route' =>  '',
        'category' =>  0,
        'sort_by' =>  0,
    ],
];
